name: Build Capsule Manager Images

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-tdx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push capsulemanager-tdx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployment/Dockerfile
          platforms: linux/amd64
          build-args: |
            PLATFORM=tdx
          tags: ghcr.io/isha42zzz/capsulemanager-tdx:4.1.2.0930
          push: true
