name: Build Capsule Manager Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-tdx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push capsulemanager-tdx image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployment/Dockerfile
          platforms: linux/amd64
          build-args: |
            PLATFORM=tdx
          tags: ghcr.io/isha42zzz/capsulemanager-tdx:4.1.2.0930
          push: true
